# fly.toml app configuration file generated for fastrat on 2024-11-19T19:39:57+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fastrat'
primary_region = 'arn'

[build]

[http_service]
  [http_service.env]
    FORWARDED_HEADERS = "true"
    PRESERVE_HEADERS = "set-cookie,cookie"
    
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[services]]
    internal_port = 3000
    protocol = "tcp"

    [[services.ports]]
      handlers = ["http"]
      port = 80

    [[services.ports]]
      handlers = ["tls", "http"]
      port = 443

    [[services.http_checks]]
      interval = "10s"
      method = "get"
      path = "/"
      protocol = "http"
      timeout = "2s"
      tls_skip_verify = false

    [[services.tcp_checks]]
      interval = "10s"
      timeout = "2s"
