# fly.toml app configuration file generated for fastrat on 2023-12-05T16:36:35+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fastrat"
primary_region = "ams"

[env]
  HOST = "0.0.0.0"
  SITE_URL = "https://www.fastrat.dev"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
