# fly.toml app configuration file generated for fastrat on 2024-11-19T18:13:45+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fastrat'
primary_region = 'ams'

[build]

[env]
  HOST = '0.0.0.0'
  HOST_NAMES_REDIRECT_FROM = 'fastrat.fly.dev,fastrat.dev'
  SITE_URL = 'https://www.fastrat.dev'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
