name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    # - uses: 'google-github-actions/auth@v2'
    #   with:
    #     credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
    #     project_id: 'fastrat'
    #     token_format: 'access_token'
    #     service_account: ${{ secrets.TEST_EMAIL }}
    - uses: actions/setup-node@v4
      with:
        node-version: 21
    - name: Install xvfb
      run: sudo apt-get install xvfb
    - name: Install dependencies
      run: npm install -g pnpm && pnpm install
    - name: Install Playwright Browsers
      run: pnpm exec playwright install --with-deps
    - name: Run Playwright tests
      run: xvfb-run --auto-servernum --server-args='-screen 0 1024x768x24' pnpm exec playwright test
      env:
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        TEST_EMAIL: ${{ secrets.TEST_EMAIL }}
        TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
        HOST: 0.0.0.0
        SECRET: b23282827-999-888c-b574-4c0eb48c8123
        TURSO_DB_URL: file:local.db
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
